### ISSUE TITLE
Discovery discovers self

### ISSUE THREAD

**Issue by kumavis** [libp2p/js-libp2p-webrtc-star#171]
`"libp2p-webrtc-star": "^0.15.8"`

sometimes accidently discovers self
```js
  // connect to all discovered nodes
  node.on('peer:discovery', (peer) => {
    // this happens i guess
    if (clientId === peer.id.toB58String()) return
    // ignore failures
    node.dial(peer, (err) => {})
  })
```

node config
```js
 const wstar = new WStar()
  const node = new Libp2p({
    peerInfo,
    modules: {
      transport: [
        WS,
        wstar
      ],
      streamMuxer: [
        Mplex
      ],
      peerDiscovery: [
        wstar.discovery,
      ],
      dht: DHT,
    },
    config: {
      peerDiscovery: {
      },
      dht: {
        enabled: true,
        kBucketSize: 20,
      },
    }
  })
```

**Comment by jacobheun** [comment]
Since transports don't always have access to their own `PeerInfo` instance (which we should probably correct by always passing the libp2p node in transport options), detecting itself on peer discovery is not reasonably possible. We should make the change at https://github.com/libp2p/js-libp2p/issues/356 to avoid downstream users from getting the event.

**Comment by jacobheun** [comment]
This has been resolved in js-libp2p
